services:
  app:
    container_name: cerberus_app
    env_file:
      - ./app/.env
    build:
      context: .infra/develop/app
      dockerfile: dev.dockerfile
    volumes:
      - ./app:/var/www/app
      - ./.infra/develop/app:/usr/local/etc/php/conf.d
    networks:
      - cerberus-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file:
      - ./app/.env
    ports:
      - "4166:3306"
    volumes:
      - db_dump:/sql
      - db_data:/var/lib/mysql
    networks:
      - cerberus-network

  redis:
    image: redis:7.2.5-alpine3.20
    command: redis-server
    networks:
      - cerberus-network
    depends_on:
      - db
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./.infra/develop/nginx
    volumes:
      - ./app:/var/www/app:delegated
      - ./.infra/develop/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.infra/develop/nginx/sites:/etc/nginx/sites-available
      - ./.infra/develop/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - '8666:80'
    networks:
      - cerberus-network
    depends_on:
      - app

volumes:
  db_data:
  db_dump:

networks:
  cerberus-network:
