apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
spec:
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app
        image: registry.digitalocean.com/charlie-container-registry/painel:1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: your-app-services
spec:
  selector:
    app: your-app
  ports:
  - name: nginx
    protocol: TCP
    port: 80
  type: ClusterIP
