apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.painel.hpaName }}
  namespace: {{ .Values.global.namespace }}
spec:
  minReplicas: {{ .Values.painel.minReplicas }}
  maxReplicas: {{ .Values.painel.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.painel.deployName }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.painel.averageUtilization }}