apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-okr
  namespace: {{ .Values.global.namespace }}
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: okr-update-command
              image: {{ .Values.global.painelImageName }}:{{ .Values.global.painelImageVersion }}
              ports:
                - containerPort: 80
              resources:
                requests:
                  cpu: {{ .Values.painel.consumerRequestCPU }}
                  memory: {{ .Values.painel.consumerRequestMemory }}
                limits:
                  cpu: {{ .Values.painel.consumerLimitsCPU }}
                  memory: {{ .Values.painel.consumerLimitsMemory }}
              imagePullPolicy: {{ .Values.global.imagePullPolicy }}
              envFrom:
                - secretRef:
                    name: {{ .Values.global.secretName }}
              volumeMounts:
                {{- include "volumeMount" . | indent 16 }}
              command:
                - sh
                - -c
                - "bin/console cron:okr:save"
          volumes:
            {{- include "volumes" . | indent 12 }}
          restartPolicy: OnFailure